apiVersion: v1
kind: Service
metadata:
  labels:
    run: air
  name: air
spec:
  ports:
  - name: "80-to-8080-tcp"
    port: 80
    targetPort: 8080
  - name: "8432-to-8432-tcp"
    port: 8432
    targetPort: 8432
  selector:
    run: air
  type: LoadBalancer
  sessionAffinity: ClientIP
