apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    run: cloak-persist
  name: cloak-persist
  namespace: aircloak
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
