apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: cloak
  name: cloak
  namespace: aircloak
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: cloak
    spec:
      containers:
      - image: quay.io/aircloak/cloak:18.3.1
        name: cloak
        volumeMounts:
        - mountPath: /runtime_config
          name: cloak-config
        - mountPath: /persist
          name: cloak-persist
      imagePullSecrets:
        - name: aircloak-external-pull-secret
      restartPolicy: Always
      volumes:
      - name: cloak-config
        configMap:
          name: cloak-configmap
          items:
            - key: config.json
              path: config.json
            - key: sample.json
              path: data_sources/sample.json
      - name: cloak-persist
        persistentVolumeClaim:
          claimName: cloak-persist
status: {}