apiVersion: v1
kind: Secret
metadata:
  name: aircloak-external-pwc-pull-secret
  namespace: aircloak
data:
  .dockerconfigjson: THIS_IS_A_VERY_SECRET_VALUE_AND_NEEDS_TO_BE_REPLACED
type: kubernetes.io/dockerconfigjson
