version: '3'
services:
  air_db:
    ports:
      - 7432:5432
    image: quay.io/aircloak/aircloak_db:latest
    volumes:
      - ./config/air_db:/runtime_config
      - ./data/air_db:/var/lib/postgresql/data
  air:
    ports:
      - 8080:8080
      - 8081:8081
      - 8432:8432
      - 8443:8443
    image: quay.io/aircloak/air:latest
    volumes:
      - ./config/air:/runtime_config
    depends_on:
      - "air_db"
  cloak:
    image: quay.io/aircloak/cloak:latest
    volumes:
      - ./config/cloak:/runtime_config
      - ./data/cloak:/persist
      - ./odbc_drivers:/odbc_drivers
    depends_on:
      - "air"
